#!/usr/bin/env bash
# Install Cloudflare Tunnel on Linux VPS for api.visionemr.net → localhost:3000
#
# Prerequisites:
#   cloudflared tunnel login   (once)
#   Docker API listening on 127.0.0.1:3000
#
# Usage:
#   bash scripts/vps/setup-api-tunnel.sh api.visionemr.net

set -euo pipefail

API_HOST="${1:-api.visionemr.net}"
TUNNEL_NAME="${TUNNEL_NAME:-cornea-emr-vps}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG="$REPO/infra/cloudflared-vps.yml"
CRED_DIR="${HOME}/.cloudflared"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "Install cloudflared first — see docs/VPS_DEPLOY.md"
  exit 1
fi

if [[ ! -f "$CRED_DIR/cert.pem" ]]; then
  echo "Run: cloudflared tunnel login"
  exit 1
fi

if ! cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  echo "Creating tunnel $TUNNEL_NAME..."
  cloudflared tunnel create "$TUNNEL_NAME"
fi

CRED_FILE="$(find "$CRED_DIR" -maxdepth 1 -name '*.json' -type f | head -1)"
if [[ -z "$CRED_FILE" ]]; then
  echo "No tunnel credentials in $CRED_DIR"
  exit 1
fi

echo "Routing DNS $API_HOST..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$API_HOST" || true

cat >"$CONFIG" <<EOF
# Auto-generated by setup-api-tunnel.sh — VPS API tunnel
tunnel: $TUNNEL_NAME
credentials-file: $CRED_FILE

ingress:
  - hostname: $API_HOST
    service: http://127.0.0.1:3000
  - service: http_status:404
EOF

echo "Wrote $CONFIG"

UNIT="/etc/systemd/system/cornea-emr-tunnel.service"
sudo tee "$UNIT" >/dev/null <<EOF
[Unit]
Description=Cloudflare Tunnel — Cornea EMR API
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
User=$USER
ExecStart=$(command -v cloudflared) tunnel --config $CONFIG run
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now cornea-emr-tunnel

echo ""
echo "Tunnel started. Test: curl https://$API_HOST/health/live"
echo "Stop the old clinic-PC tunnel if still running."
