# API-only Cloudflare Tunnel for Cornea EMR.
# Clinic UI is served by Cloudflare Workers (corneaclinic.visionemr.net).
# This script exposes only the local API (port 3000) at api.visionemr.net.
#
# Prerequisites:
#   cloudflared tunnel login   (once, opens browser)
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\setup-cloudflare-api-tunnel.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\setup-cloudflare-api-tunnel.ps1 -ApiHost api.visionemr.net

param(
    [string]$ApiHost = 'api.visionemr.net',
    [string]$ClinicUrl = 'https://corneaclinic.visionemr.net',
    [string]$TunnelName = 'cornea-clinic'
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $RepoRoot 'apps\api\.env'
$ConfigOut = Join-Path $RepoRoot 'infra\cloudflared-config.yml'

$env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
            [System.Environment]::GetEnvironmentVariable('Path', 'User')

if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
    Write-Error 'cloudflared not found. Run scripts\install-cloudflared.ps1 first.'
    exit 1
}

$credDir = Join-Path $env:USERPROFILE '.cloudflared'
if (-not (Test-Path (Join-Path $credDir 'cert.pem'))) {
    Write-Host 'Not logged in to Cloudflare. Run this first (opens browser):' -ForegroundColor Yellow
    Write-Host '  cloudflared tunnel login'
    exit 1
}

$apiUrl = "https://$ApiHost"

Write-Host '=== Cornea EMR - API tunnel setup ===' -ForegroundColor Cyan
Write-Host "API hostname: $ApiHost"
Write-Host ('Clinic UI:    ' + $ClinicUrl + ' (Workers, not tunneled)')
Write-Host ''

Write-Host "Creating tunnel '$TunnelName' if needed..."
$tunnelList = & cloudflared tunnel list 2>&1 | Out-String
if ($tunnelList -notmatch [regex]::Escape($TunnelName)) {
    & cloudflared tunnel create $TunnelName
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

$credFile = Get-ChildItem $credDir -Filter '*.json' -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^[0-9a-f-]+\.json$' } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $credFile) {
    Write-Error "No tunnel credentials in $credDir - run: cloudflared tunnel create $TunnelName"
    exit 1
}

Write-Host "Routing DNS: $ApiHost"
$prevEap = $ErrorActionPreference
$ErrorActionPreference = 'Continue'
& cloudflared tunnel route dns $TunnelName $ApiHost 2>&1 | Write-Host
$ErrorActionPreference = $prevEap

$config = @"
# Auto-generated by setup-cloudflare-api-tunnel.ps1
# Clinic UI: Cloudflare Workers ($ClinicUrl)
tunnel: $TunnelName
credentials-file: $($credFile.FullName)

ingress:
  - hostname: $ApiHost
    service: http://127.0.0.1:3000
  - service: http_status:404
"@
Set-Content -Path $ConfigOut -Value $config -Encoding UTF8
Write-Host "Wrote $ConfigOut" -ForegroundColor Green

if (Test-Path $EnvFile) {
    $cors = "$ClinicUrl,http://127.0.0.1:8080,http://localhost:8080"
    $lines = Get-Content $EnvFile
    $map = @{
        'CORS_ORIGIN'    = $cors
        'APP_PUBLIC_URL' = $apiUrl
    }
    $out = @()
    $seen = @{}
    foreach ($line in $lines) {
        $matched = $false
        foreach ($key in $map.Keys) {
            if ($line -match "^\s*$key\s*=") {
                $out += "$key=$($map[$key])"
                $seen[$key] = $true
                $matched = $true
                break
            }
        }
        if (-not $matched) { $out += $line }
    }
    foreach ($key in $map.Keys) {
        if (-not $seen[$key]) { $out += "$key=$($map[$key])" }
    }
    Set-Content -Path $EnvFile -Value $out -Encoding UTF8
    Write-Host 'Updated apps/api/.env' -ForegroundColor Green
}

Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host '  1. Restart stack:  scripts\restart-production-stack.ps1'
Write-Host '  2. Install tunnel:  scripts\install-cloudflare-tunnel-service.ps1'
Write-Host ''
Write-Host "Test:  $apiUrl/health/live"
