# Create Cloudflare Tunnel for public Cornea Clinic access.
#
# Prerequisites:
#   1. Domain DNS managed by Cloudflare
#   2. cloudflared tunnel login   (once)
#   3. Clinic PC running API (:3000) and UI server (:8080)
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\setup-cloudflare-tunnel.ps1

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$EnvFile  = Join-Path $RepoRoot 'apps\api\.env'
$Adapter  = Join-Path $RepoRoot 'apps\clinic\cornea-api-adapter.js'
$ConfigOut = Join-Path $RepoRoot 'infra\cloudflared-config.yml'
$TunnelName = 'cornea-clinic'

$env:Path = [System.Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
            [System.Environment]::GetEnvironmentVariable('Path', 'User')

if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
    Write-Host 'cloudflared not found. Run scripts\install-cloudflared.ps1 first.' -ForegroundColor Yellow
    exit 1
}

Write-Host '=== Cornea Clinic — public internet setup ===' -ForegroundColor Cyan
Write-Host ''
Write-Host 'You need a domain on Cloudflare (free account).'
Write-Host 'If not logged in yet, run:  cloudflared tunnel login'
Write-Host ''

$clinicHost = Read-Host 'Clinic UI hostname (e.g. clinic.yourdomain.com)'
$apiHost    = Read-Host 'API hostname (e.g. api.yourdomain.com)'
if (-not $clinicHost -or -not $apiHost) {
    Write-Error 'Both hostnames are required.'
    exit 1
}

$clinicUrl = "https://$clinicHost"
$apiUrl    = "https://$apiHost"

Write-Host ''
Write-Host "Creating tunnel '$TunnelName' if needed..."
$tunnelList = & cloudflared tunnel list 2>&1 | Out-String
if ($tunnelList -notmatch [regex]::Escape($TunnelName)) {
    & cloudflared tunnel create $TunnelName
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

$credDir = Join-Path $env:USERPROFILE '.cloudflared'
$credFile = Get-ChildItem $credDir -Filter '*.json' -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match '^[0-9a-f-]+\.json$' } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $credFile) {
    Write-Error "No tunnel credentials in $credDir — run: cloudflared tunnel create $TunnelName"
    exit 1
}

Write-Host "Routing DNS: $clinicHost"
& cloudflared tunnel route dns $TunnelName $clinicHost 2>&1 | Write-Host
Write-Host "Routing DNS: $apiHost"
& cloudflared tunnel route dns $TunnelName $apiHost 2>&1 | Write-Host

$config = @"
# Auto-generated by setup-cloudflare-tunnel.ps1
tunnel: $TunnelName
credentials-file: $($credFile.FullName)

ingress:
  - hostname: $clinicHost
    service: http://127.0.0.1:8080
  - hostname: $apiHost
    service: http://127.0.0.1:3000
  - service: http_status:404
"@
Set-Content -Path $ConfigOut -Value $config -Encoding UTF8
Write-Host "Wrote $ConfigOut" -ForegroundColor Green

# --- Update apps/api/.env ---
if (Test-Path $EnvFile) {
    $cors = "$clinicUrl,http://127.0.0.1:8080,http://localhost:8080"
    $lines = Get-Content $EnvFile
    $map = @{
        'CORS_ORIGIN'    = $cors
        'APP_PUBLIC_URL' = $apiUrl
    }
    $out = @()
    $seen = @{}
    foreach ($line in $lines) {
        $matched = $false
        foreach ($key in $map.Keys) {
            if ($line -match "^\s*$key\s*=") {
                $out += "$key=$($map[$key])"
                $seen[$key] = $true
                $matched = $true
                break
            }
        }
        if (-not $matched) { $out += $line }
    }
    foreach ($key in $map.Keys) {
        if (-not $seen[$key]) { $out += "$key=$($map[$key])" }
    }
    Set-Content -Path $EnvFile -Value $out -Encoding UTF8
    Write-Host 'Updated apps/api/.env (CORS_ORIGIN, APP_PUBLIC_URL)' -ForegroundColor Green
}

# --- Update frontend default API URL ---
if (Test-Path $Adapter) {
    $adapterText = Get-Content $Adapter -Raw
    $newAdapter = $adapterText -replace "const DEFAULT_API_BASE = '[^']*';", "const DEFAULT_API_BASE = '$apiUrl';"
    if ($newAdapter -ne $adapterText) {
        Set-Content -Path $Adapter -Value $newAdapter -Encoding UTF8 -NoNewline
        Write-Host 'Updated cornea-api-adapter.js DEFAULT_API_BASE' -ForegroundColor Green
    }
}

Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host "  1. Restart API:  Stop-ScheduledTask CorneaEMR-API; Start-ScheduledTask CorneaEMR-API"
Write-Host '  2. Install tunnel service:  scripts\install-cloudflare-tunnel-service.ps1'
Write-Host "  3. Start clinic UI:  apps\clinic\start-clinic.bat"
Write-Host ''
Write-Host "Public URLs:"
Write-Host "  Clinic:  $clinicUrl/Cornea.html"
Write-Host "  API:     $apiUrl/health/live"
Write-Host ''
Write-Host 'See docs/PUBLIC_INTERNET_ACCESS.md for Cloudflare Access (recommended).'
